const s = '小木马二代车硬件通信协议V1.2\n' +
  '1\t版本记录\n' +
  '版本号\t修改点\t修改人\n' +
  'V1.0\t梳理通讯协议\t李庆春\n' +
  'V1.1\t1.\t去掉多余的关锁开关\n' +
  '2.\t开关锁等协议的调整\n' +
  '3.\t升级协议的调整\t李庆春\n' +
  'V1.2\t1.\t升级传输的分页报文规范和校验。\n' +
  '2.\t主PAD去掉通电启动的逻辑，和定时关机的逻辑。\t李庆春\n' +
  '\n' +
  '2\t通信规范\n' +
  '2.1\t通信架构\n' +
  ' \n' +
  '2.1\t模块解释\n' +
  '2.1.1\t控制板\n' +
  '控制板是整个车载硬件系统的核心，内嵌STM8S207K8单片机芯片，开放特定的端口和外部各个器件物理连接，通过单片机上的主程序和控制板上的物理电路控制各个器件。\n' +
  '2.1.2\t主PAD\n' +
  '主PAD是车载后置安卓PAD，安装位置在推车的扶手处。主PAD是用户的主要接口，用户通过主PAD进行开锁、暂停、关锁等一系列动作。通过5pin导线和控制板连接，其中3pin用于数据通信，2pin用于电源供给。\n' +
  '主PAD需要具备特性：1.定时开机。\n' +
  '2.1.3\t有源喇叭\n' +
  '有源喇叭的音频输入和主PAD的耳机口相连，电源输入通过2pin导线和控制板连接。单片机的2pin端口充当开关的角色，根据主PAD的命令决定是否连接到大电池的输出。\n' +
  '2.1.4\t大电池\n' +
  '大电池是主要的电源供给方，通过降压模块对主PAD、前部儿童PAD、小电池进行供电。\n' +
  '2.1.5\t前部儿童PAD\n' +
  '前部儿童PAD是坐在推车上的儿童的娱乐设施，通过USB和控制板连接，USB口充当电源开关的角色，单片机根据主PAD的命令决定是否为前部儿童PAD供电。\n' +
  '前部儿童PAD需要修改启动项，当检测到外部供电时，则启动系统。\n' +
  '2.1.6\t小电池\n' +
  '小电池责给控制板、有源喇叭、电机供电。\n' +
  '2.1.7\t锁\n' +
  '控制板接两组锁模块，每组包含：一个电机、一个关锁检测开关。主控制板根据主PAD下发的命令驱动电机正转或反转，并同时检测状态开关。锁的状态包括：打开、关闭、开锁中、关锁中。\n' +
  '2.1.8\t其他状态检测开关\n' +
  '其他状态检测包括：还车桩检测开关、安全带检测开关、预留的检测开关。三者承担的角色功能是一致的，都是检测pin口的电平输入，已确定相关器件是否物理连接。\n' +
  '2.2\t通信方式\n' +
  'PAD与SCM通过串口线直接连接，通过串口（UART）直接通讯。SCM周期性地自主睡眠和唤醒，一个时间周期为1.2秒，其中睡眠时间1秒和唤醒时间0.2秒。在SCM的唤醒时，SCM主动向PAD发送状态报文。PAD接收到状态报文后，才能检测到SCM处于唤醒状态，继而可以在这段唤醒时间内发送命令给SCM。\n' +
  '2.3\t报文结构\n' +
  '一个完整的报文包含三个部分：命令字、消息体、结束标志，三者通过英文冒号（:）分隔，依次排列构成一个字符序列。\n' +
  '命令字\t消息体\t结束标志\n' +
  '命令字：数据类型为字符序列，表示需要执行的动作。\n' +
  '消息体：数据类型为字符序列，表示命令需要携带的数据，如果有多个字段的数据，则用英文逗号（,）进行分隔。\n' +
  '结束标志：\\r\\n。\n' +
  '报文样例：\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,2018.01.06,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3\t通信命令\n' +
  '3.1\t开锁\n' +
  '3.1.1\t场景描述\n' +
  '当只有关锁检测开关时，锁模块包含两个核心组件：一个马达和一个关锁检测开关。锁的状态有两种：打开和关闭。当关锁检测开关为闭合状态时，认为锁是关闭状态，否则认为锁是打开状态。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送开锁请求命令。\n' +
  '3.\tSCM接收到开锁请求命令后，返回ACK，告知已收到消息。\n' +
  '4.\tSCM检测当前状态：\n' +
  'a)\t如果两个锁的状态都是开着的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是开着的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  'ii.\t如果锁2是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  '5.\t检测两个锁的状态。\n' +
  '6.\tSCM发送开锁结果给PAD。\n' +
  ' \n' +
  '\n' +
  '3.1.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.1.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.1.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_RES:UNLOCKED,UNLOCKED:\\r\\n\n' +
  '\n' +
  '3.2\t关锁\n' +
  '3.2.1\t场景描述\n' +
  '一个锁的模块包括：一个电机和一个关锁检测开关，在关锁的时候我们只需要判断关锁检测开关是否被压到，就可以确认是否关锁成功。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送关锁请求命令。\n' +
  '3.\tSCM接收到关锁请求命令后，发送ACK命令。\n' +
  '4.\t检测当前状态：\n' +
  'a)\t如果两个锁的状态都是关闭的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是关闭的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非关闭状态，则向锁1输出反向电平固定时长（暂定3秒，具体时间后续根据实验数据进行调整），如果在这段时间内监听到锁1的中断消息，则执行：\n' +
  '1.\t当前时间的基础上继续给锁输出反向电平0.5秒，以使得开关被压到底，然后取消供电。 \n' +
  'ii.\t如果锁2是非关闭状态，则执行逻辑同上。\n' +
  '5.\t检测两个锁的状态。 \n' +
  '6.\tSCM发送关锁结果给PAD。\n' +
  ' \n' +
  '3.2.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.2.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.2.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_RES:LOCKED,LOCKED:\\r\\n\n' +
  '\n' +
  '3.3\t固件升级\n' +
  '3.3.1\t场景描述\n' +
  '在SCM的使用过程中，会由于业务需求或者修复问题的情况，需要对SCM程序进行升级。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送固件升级请求命令。\n' +
  '3.\tSCM发送请求的ACK。\n' +
  '4.\tPAD和SCM同时执行：\n' +
  'a)\tPAD在6秒内轮询，每隔一秒向SCM发送“BOOT_READY”命令，询问SCM是否准备好，如果接收到SCM的ACK，则跳至步骤5。\n' +
  'b)\tSCM重启，进入BootLoader，然后监听PAD的BOOT_READY，接收后发送“BOOT_READY_ACK”。\n' +
  '5.\tPAD分页输送升级程序给SCM，从第一页开始，直至发送到最后一页，循环执行以下动作序列：\n' +
  'a)\tPAD发送当前页码命令给SCM：“PAGE_INDEX_<page_index>“。\n' +
  'b)\tSCM回复确认给PAD：“PAGE_INDEX_ACK“。\n' +
  'c)\tPAD发送当前页数据给SCM：<page_data>。\n' +
  'd)\tSCM回复确认给PAD：“PAGE_DATA_ACK”\n' +
  '6.\tPAD发送命令“DATA_DONE”给SCM，告知其所有分页数据以传输完成。\n' +
  '7.\tSCM回复确认“DATA_DONE_ACK”给PAD。\n' +
  '8.\tSCM使用新的升级程序进行升级。\n' +
  ' \n' +
  '3.3.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ::\\r\\n\n' +
  '\n' +
  '3.3.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.4\t状态上报\n' +
  '3.4.1\t场景描述\n' +
  'SCM自身会进行周期性的睡眠和自我唤醒，当SCM由睡眠状态切换到唤醒状态时，需要告知PAD，方便PAD发送命令给SCM。\n' +
  '同时出于业务的需要，携带一些设备的状态数据，包括但不限于：电池电量、两把锁的状态、SCM程序版本号、SCM芯片ID、一些检测开关的状态。\n' +
  '3.4.2\t请求报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSTATUS_REPORT\n' +
  'power\tint\t电池电量\t1-100\n' +
  'lock1Status\tString\t一个锁状态\tLOCKED\n' +
  'UNLOCKED、\n' +
  'lock2Status\tString\t另一个锁状态\t同上\n' +
  'speakerStatus\tString\t扬声器状态\tCONNECTED\n' +
  'DISCONNECTED\n' +
  'padfStatus\tString\t前置PAD状态\t同上\n' +
  'parkingPileStatus\tString\t停车桩状态\t同上\n' +
  'seatBeltStatus\tString\t安全带状态\t同上\n' +
  'reservedStatus\tString\t预留开关的状态\t同上\n' +
  'softVersion\tString\t软件版本\t版本号用日期格式如：2018.01.06\n' +
  'hardVersion\tString\t硬件版本\t如：2G（表示二代主板）\n' +
  'chipId\tString\t芯片ID\t\n' +
  '\n' +
  '报文样例\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,CONNECTED，CONNECTED，CONNECTED,DISCONNECTED,DISCONNECTED,2018.01.06,2G,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3.5\t接通喇叭\n' +
  '3.5.1\t场景描述\n' +
  '当需要播放特定音频内容的时候，需要为外部的有源喇叭接通电源，使其工作。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通喇叭请求命令。\n' +
  '3.\tSCM接通有源喇叭外部电源，返回成功给PAD。\n' +
  '3.5.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.5.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.6\t断开喇叭\n' +
  '3.6.1\t场景描述\n' +
  '当完成音频播放后，出于节省功耗的考虑，需要尽快断开有源喇叭的电源供给。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开喇叭请求命令。\n' +
  '3.\tSCM断开有源喇叭外接电源，返回成功给PAD。\n' +
  '3.6.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_ DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.6.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.7\t接通前置PAD\n' +
  '3.7.1\t场景描述\n' +
  '当用户付费使用推车产品时，需要对前置PAD接通电源，以使其从关机状态下启动，供儿童娱乐。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通前置PAD请求命令。\n' +
  '3.\tSCM接通前置PAD外部电源，返回成功给PAD。\n' +
  '3.7.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.7.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.8\t断开前置PAD\n' +
  '3.8.1\t场景描述\n' +
  '当用户结束使用推车产品时，需要对前置PAD断开电源，以使云端可以发送命令使其从关机并不再自动重启。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开前置PAD请求命令。\n' +
  '3.\tSCM断开前置PAD外部电源，返回成功给PAD。\n' +
  '3.8.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.8.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '1\t版本记录\n' +
  '版本号\t修改点\t修改人\n' +
  'V1.0\t梳理通讯协议\t李庆春\n' +
  'V1.1\t1.\t去掉多余的关锁开关\n' +
  '2.\t开关锁等协议的调整\n' +
  '3.\t升级协议的调整\t李庆春\n' +
  'V1.2\t1.\t升级传输的分页报文规范和校验。\n' +
  '2.\t主PAD去掉通电启动的逻辑，和定时关机的逻辑。\t李庆春\n' +
  '\n' +
  '2\t通信规范\n' +
  '2.1\t通信架构\n' +
  ' \n' +
  '2.1\t模块解释\n' +
  '2.1.1\t控制板\n' +
  '控制板是整个车载硬件系统的核心，内嵌STM8S207K8单片机芯片，开放特定的端口和外部各个器件物理连接，通过单片机上的主程序和控制板上的物理电路控制各个器件。\n' +
  '2.1.2\t主PAD\n' +
  '主PAD是车载后置安卓PAD，安装位置在推车的扶手处。主PAD是用户的主要接口，用户通过主PAD进行开锁、暂停、关锁等一系列动作。通过5pin导线和控制板连接，其中3pin用于数据通信，2pin用于电源供给。\n' +
  '主PAD需要具备特性：1.定时开机。\n' +
  '2.1.3\t有源喇叭\n' +
  '有源喇叭的音频输入和主PAD的耳机口相连，电源输入通过2pin导线和控制板连接。单片机的2pin端口充当开关的角色，根据主PAD的命令决定是否连接到大电池的输出。\n' +
  '2.1.4\t大电池\n' +
  '大电池是主要的电源供给方，通过降压模块对主PAD、前部儿童PAD、小电池进行供电。\n' +
  '2.1.5\t前部儿童PAD\n' +
  '前部儿童PAD是坐在推车上的儿童的娱乐设施，通过USB和控制板连接，USB口充当电源开关的角色，单片机根据主PAD的命令决定是否为前部儿童PAD供电。\n' +
  '前部儿童PAD需要修改启动项，当检测到外部供电时，则启动系统。\n' +
  '2.1.6\t小电池\n' +
  '小电池责给控制板、有源喇叭、电机供电。\n' +
  '2.1.7\t锁\n' +
  '控制板接两组锁模块，每组包含：一个电机、一个关锁检测开关。主控制板根据主PAD下发的命令驱动电机正转或反转，并同时检测状态开关。锁的状态包括：打开、关闭、开锁中、关锁中。\n' +
  '2.1.8\t其他状态检测开关\n' +
  '其他状态检测包括：还车桩检测开关、安全带检测开关、预留的检测开关。三者承担的角色功能是一致的，都是检测pin口的电平输入，已确定相关器件是否物理连接。\n' +
  '2.2\t通信方式\n' +
  'PAD与SCM通过串口线直接连接，通过串口（UART）直接通讯。SCM周期性地自主睡眠和唤醒，一个时间周期为1.2秒，其中睡眠时间1秒和唤醒时间0.2秒。在SCM的唤醒时，SCM主动向PAD发送状态报文。PAD接收到状态报文后，才能检测到SCM处于唤醒状态，继而可以在这段唤醒时间内发送命令给SCM。\n' +
  '2.3\t报文结构\n' +
  '一个完整的报文包含三个部分：命令字、消息体、结束标志，三者通过英文冒号（:）分隔，依次排列构成一个字符序列。\n' +
  '命令字\t消息体\t结束标志\n' +
  '命令字：数据类型为字符序列，表示需要执行的动作。\n' +
  '消息体：数据类型为字符序列，表示命令需要携带的数据，如果有多个字段的数据，则用英文逗号（,）进行分隔。\n' +
  '结束标志：\\r\\n。\n' +
  '报文样例：\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,2018.01.06,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3\t通信命令\n' +
  '3.1\t开锁\n' +
  '3.1.1\t场景描述\n' +
  '当只有关锁检测开关时，锁模块包含两个核心组件：一个马达和一个关锁检测开关。锁的状态有两种：打开和关闭。当关锁检测开关为闭合状态时，认为锁是关闭状态，否则认为锁是打开状态。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送开锁请求命令。\n' +
  '3.\tSCM接收到开锁请求命令后，返回ACK，告知已收到消息。\n' +
  '4.\tSCM检测当前状态：\n' +
  'a)\t如果两个锁的状态都是开着的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是开着的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  'ii.\t如果锁2是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  '5.\t检测两个锁的状态。\n' +
  '6.\tSCM发送开锁结果给PAD。\n' +
  ' \n' +
  '\n' +
  '3.1.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.1.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.1.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_RES:UNLOCKED,UNLOCKED:\\r\\n\n' +
  '\n' +
  '3.2\t关锁\n' +
  '3.2.1\t场景描述\n' +
  '一个锁的模块包括：一个电机和一个关锁检测开关，在关锁的时候我们只需要判断关锁检测开关是否被压到，就可以确认是否关锁成功。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送关锁请求命令。\n' +
  '3.\tSCM接收到关锁请求命令后，发送ACK命令。\n' +
  '4.\t检测当前状态：\n' +
  'a)\t如果两个锁的状态都是关闭的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是关闭的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非关闭状态，则向锁1输出反向电平固定时长（暂定3秒，具体时间后续根据实验数据进行调整），如果在这段时间内监听到锁1的中断消息，则执行：\n' +
  '1.\t当前时间的基础上继续给锁输出反向电平0.5秒，以使得开关被压到底，然后取消供电。 \n' +
  'ii.\t如果锁2是非关闭状态，则执行逻辑同上。\n' +
  '5.\t检测两个锁的状态。 \n' +
  '6.\tSCM发送关锁结果给PAD。\n' +
  ' \n' +
  '3.2.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.2.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.2.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_RES:LOCKED,LOCKED:\\r\\n\n' +
  '\n' +
  '3.3\t固件升级\n' +
  '3.3.1\t场景描述\n' +
  '在SCM的使用过程中，会由于业务需求或者修复问题的情况，需要对SCM程序进行升级。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送固件升级请求命令。\n' +
  '3.\tSCM发送请求的ACK。\n' +
  '4.\tPAD和SCM同时执行：\n' +
  'a)\tPAD在6秒内轮询，每隔一秒向SCM发送“BOOT_READY”命令，询问SCM是否准备好，如果接收到SCM的ACK，则跳至步骤5。\n' +
  'b)\tSCM重启，进入BootLoader，然后监听PAD的BOOT_READY，接收后发送“BOOT_READY_ACK”。\n' +
  '5.\tPAD分页输送升级程序给SCM，从第一页开始，直至发送到最后一页，循环执行以下动作序列：\n' +
  'a)\tPAD发送当前页码命令给SCM：“PAGE_INDEX_<page_index>“。\n' +
  'b)\tSCM回复确认给PAD：“PAGE_INDEX_ACK“。\n' +
  'c)\tPAD发送当前页数据给SCM：<page_data>。\n' +
  'd)\tSCM回复确认给PAD：“PAGE_DATA_ACK”\n' +
  '6.\tPAD发送命令“DATA_DONE”给SCM，告知其所有分页数据以传输完成。\n' +
  '7.\tSCM回复确认“DATA_DONE_ACK”给PAD。\n' +
  '8.\tSCM使用新的升级程序进行升级。\n' +
  ' \n' +
  '3.3.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ::\\r\\n\n' +
  '\n' +
  '3.3.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.4\t状态上报\n' +
  '3.4.1\t场景描述\n' +
  'SCM自身会进行周期性的睡眠和自我唤醒，当SCM由睡眠状态切换到唤醒状态时，需要告知PAD，方便PAD发送命令给SCM。\n' +
  '同时出于业务的需要，携带一些设备的状态数据，包括但不限于：电池电量、两把锁的状态、SCM程序版本号、SCM芯片ID、一些检测开关的状态。\n' +
  '3.4.2\t请求报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSTATUS_REPORT\n' +
  'power\tint\t电池电量\t1-100\n' +
  'lock1Status\tString\t一个锁状态\tLOCKED\n' +
  'UNLOCKED、\n' +
  'lock2Status\tString\t另一个锁状态\t同上\n' +
  'speakerStatus\tString\t扬声器状态\tCONNECTED\n' +
  'DISCONNECTED\n' +
  'padfStatus\tString\t前置PAD状态\t同上\n' +
  'parkingPileStatus\tString\t停车桩状态\t同上\n' +
  'seatBeltStatus\tString\t安全带状态\t同上\n' +
  'reservedStatus\tString\t预留开关的状态\t同上\n' +
  'softVersion\tString\t软件版本\t版本号用日期格式如：2018.01.06\n' +
  'hardVersion\tString\t硬件版本\t如：2G（表示二代主板）\n' +
  'chipId\tString\t芯片ID\t\n' +
  '\n' +
  '报文样例\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,CONNECTED，CONNECTED，CONNECTED,DISCONNECTED,DISCONNECTED,2018.01.06,2G,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3.5\t接通喇叭\n' +
  '3.5.1\t场景描述\n' +
  '当需要播放特定音频内容的时候，需要为外部的有源喇叭接通电源，使其工作。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通喇叭请求命令。\n' +
  '3.\tSCM接通有源喇叭外部电源，返回成功给PAD。\n' +
  '3.5.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.5.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.6\t断开喇叭\n' +
  '3.6.1\t场景描述\n' +
  '当完成音频播放后，出于节省功耗的考虑，需要尽快断开有源喇叭的电源供给。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开喇叭请求命令。\n' +
  '3.\tSCM断开有源喇叭外接电源，返回成功给PAD。\n' +
  '3.6.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_ DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.6.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.7\t接通前置PAD\n' +
  '3.7.1\t场景描述\n' +
  '当用户付费使用推车产品时，需要对前置PAD接通电源，以使其从关机状态下启动，供儿童娱乐。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通前置PAD请求命令。\n' +
  '3.\tSCM接通前置PAD外部电源，返回成功给PAD。\n' +
  '3.7.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.7.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.8\t断开前置PAD\n' +
  '3.8.1\t场景描述\n' +
  '当用户结束使用推车产品时，需要对前置PAD断开电源，以使云端可以发送命令使其从关机并不再自动重启。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开前置PAD请求命令。\n' +
  '3.\tSCM断开前置PAD外部电源，返回成功给PAD。\n' +
  '3.8.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.8.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '1\t版本记录\n' +
  '版本号\t修改点\t修改人\n' +
  'V1.0\t梳理通讯协议\t李庆春\n' +
  'V1.1\t1.\t去掉多余的关锁开关\n' +
  '2.\t开关锁等协议的调整\n' +
  '3.\t升级协议的调整\t李庆春\n' +
  'V1.2\t1.\t升级传输的分页报文规范和校验。\n' +
  '2.\t主PAD去掉通电启动的逻辑，和定时关机的逻辑。\t李庆春\n' +
  '\n' +
  '2\t通信规范\n' +
  '2.1\t通信架构\n' +
  ' \n' +
  '2.1\t模块解释\n' +
  '2.1.1\t控制板\n' +
  '控制板是整个车载硬件系统的核心，内嵌STM8S207K8单片机芯片，开放特定的端口和外部各个器件物理连接，通过单片机上的主程序和控制板上的物理电路控制各个器件。\n' +
  '2.1.2\t主PAD\n' +
  '主PAD是车载后置安卓PAD，安装位置在推车的扶手处。主PAD是用户的主要接口，用户通过主PAD进行开锁、暂停、关锁等一系列动作。通过5pin导线和控制板连接，其中3pin用于数据通信，2pin用于电源供给。\n' +
  '主PAD需要具备特性：1.定时开机。\n' +
  '2.1.3\t有源喇叭\n' +
  '有源喇叭的音频输入和主PAD的耳机口相连，电源输入通过2pin导线和控制板连接。单片机的2pin端口充当开关的角色，根据主PAD的命令决定是否连接到大电池的输出。\n' +
  '2.1.4\t大电池\n' +
  '大电池是主要的电源供给方，通过降压模块对主PAD、前部儿童PAD、小电池进行供电。\n' +
  '2.1.5\t前部儿童PAD\n' +
  '前部儿童PAD是坐在推车上的儿童的娱乐设施，通过USB和控制板连接，USB口充当电源开关的角色，单片机根据主PAD的命令决定是否为前部儿童PAD供电。\n' +
  '前部儿童PAD需要修改启动项，当检测到外部供电时，则启动系统。\n' +
  '2.1.6\t小电池\n' +
  '小电池责给控制板、有源喇叭、电机供电。\n' +
  '2.1.7\t锁\n' +
  '控制板接两组锁模块，每组包含：一个电机、一个关锁检测开关。主控制板根据主PAD下发的命令驱动电机正转或反转，并同时检测状态开关。锁的状态包括：打开、关闭、开锁中、关锁中。\n' +
  '2.1.8\t其他状态检测开关\n' +
  '其他状态检测包括：还车桩检测开关、安全带检测开关、预留的检测开关。三者承担的角色功能是一致的，都是检测pin口的电平输入，已确定相关器件是否物理连接。\n' +
  '2.2\t通信方式\n' +
  'PAD与SCM通过串口线直接连接，通过串口（UART）直接通讯。SCM周期性地自主睡眠和唤醒，一个时间周期为1.2秒，其中睡眠时间1秒和唤醒时间0.2秒。在SCM的唤醒时，SCM主动向PAD发送状态报文。PAD接收到状态报文后，才能检测到SCM处于唤醒状态，继而可以在这段唤醒时间内发送命令给SCM。\n' +
  '2.3\t报文结构\n' +
  '一个完整的报文包含三个部分：命令字、消息体、结束标志，三者通过英文冒号（:）分隔，依次排列构成一个字符序列。\n' +
  '命令字\t消息体\t结束标志\n' +
  '命令字：数据类型为字符序列，表示需要执行的动作。\n' +
  '消息体：数据类型为字符序列，表示命令需要携带的数据，如果有多个字段的数据，则用英文逗号（,）进行分隔。\n' +
  '结束标志：\\r\\n。\n' +
  '报文样例：\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,2018.01.06,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3\t通信命令\n' +
  '3.1\t开锁\n' +
  '3.1.1\t场景描述\n' +
  '当只有关锁检测开关时，锁模块包含两个核心组件：一个马达和一个关锁检测开关。锁的状态有两种：打开和关闭。当关锁检测开关为闭合状态时，认为锁是关闭状态，否则认为锁是打开状态。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送开锁请求命令。\n' +
  '3.\tSCM接收到开锁请求命令后，返回ACK，告知已收到消息。\n' +
  '4.\tSCM检测当前状态：\n' +
  'a)\t如果两个锁的状态都是开着的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是开着的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  'ii.\t如果锁2是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  '5.\t检测两个锁的状态。\n' +
  '6.\tSCM发送开锁结果给PAD。\n' +
  ' \n' +
  '\n' +
  '3.1.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.1.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.1.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_RES:UNLOCKED,UNLOCKED:\\r\\n\n' +
  '\n' +
  '3.2\t关锁\n' +
  '3.2.1\t场景描述\n' +
  '一个锁的模块包括：一个电机和一个关锁检测开关，在关锁的时候我们只需要判断关锁检测开关是否被压到，就可以确认是否关锁成功。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送关锁请求命令。\n' +
  '3.\tSCM接收到关锁请求命令后，发送ACK命令。\n' +
  '4.\t检测当前状态：\n' +
  'a)\t如果两个锁的状态都是关闭的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是关闭的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非关闭状态，则向锁1输出反向电平固定时长（暂定3秒，具体时间后续根据实验数据进行调整），如果在这段时间内监听到锁1的中断消息，则执行：\n' +
  '1.\t当前时间的基础上继续给锁输出反向电平0.5秒，以使得开关被压到底，然后取消供电。 \n' +
  'ii.\t如果锁2是非关闭状态，则执行逻辑同上。\n' +
  '5.\t检测两个锁的状态。 \n' +
  '6.\tSCM发送关锁结果给PAD。\n' +
  ' \n' +
  '3.2.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.2.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.2.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_RES:LOCKED,LOCKED:\\r\\n\n' +
  '\n' +
  '3.3\t固件升级\n' +
  '3.3.1\t场景描述\n' +
  '在SCM的使用过程中，会由于业务需求或者修复问题的情况，需要对SCM程序进行升级。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送固件升级请求命令。\n' +
  '3.\tSCM发送请求的ACK。\n' +
  '4.\tPAD和SCM同时执行：\n' +
  'a)\tPAD在6秒内轮询，每隔一秒向SCM发送“BOOT_READY”命令，询问SCM是否准备好，如果接收到SCM的ACK，则跳至步骤5。\n' +
  'b)\tSCM重启，进入BootLoader，然后监听PAD的BOOT_READY，接收后发送“BOOT_READY_ACK”。\n' +
  '5.\tPAD分页输送升级程序给SCM，从第一页开始，直至发送到最后一页，循环执行以下动作序列：\n' +
  'a)\tPAD发送当前页码命令给SCM：“PAGE_INDEX_<page_index>“。\n' +
  'b)\tSCM回复确认给PAD：“PAGE_INDEX_ACK“。\n' +
  'c)\tPAD发送当前页数据给SCM：<page_data>。\n' +
  'd)\tSCM回复确认给PAD：“PAGE_DATA_ACK”\n' +
  '6.\tPAD发送命令“DATA_DONE”给SCM，告知其所有分页数据以传输完成。\n' +
  '7.\tSCM回复确认“DATA_DONE_ACK”给PAD。\n' +
  '8.\tSCM使用新的升级程序进行升级。\n' +
  ' \n' +
  '3.3.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ::\\r\\n\n' +
  '\n' +
  '3.3.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.4\t状态上报\n' +
  '3.4.1\t场景描述\n' +
  'SCM自身会进行周期性的睡眠和自我唤醒，当SCM由睡眠状态切换到唤醒状态时，需要告知PAD，方便PAD发送命令给SCM。\n' +
  '同时出于业务的需要，携带一些设备的状态数据，包括但不限于：电池电量、两把锁的状态、SCM程序版本号、SCM芯片ID、一些检测开关的状态。\n' +
  '3.4.2\t请求报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSTATUS_REPORT\n' +
  'power\tint\t电池电量\t1-100\n' +
  'lock1Status\tString\t一个锁状态\tLOCKED\n' +
  'UNLOCKED、\n' +
  'lock2Status\tString\t另一个锁状态\t同上\n' +
  'speakerStatus\tString\t扬声器状态\tCONNECTED\n' +
  'DISCONNECTED\n' +
  'padfStatus\tString\t前置PAD状态\t同上\n' +
  'parkingPileStatus\tString\t停车桩状态\t同上\n' +
  'seatBeltStatus\tString\t安全带状态\t同上\n' +
  'reservedStatus\tString\t预留开关的状态\t同上\n' +
  'softVersion\tString\t软件版本\t版本号用日期格式如：2018.01.06\n' +
  'hardVersion\tString\t硬件版本\t如：2G（表示二代主板）\n' +
  'chipId\tString\t芯片ID\t\n' +
  '\n' +
  '报文样例\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,CONNECTED，CONNECTED，CONNECTED,DISCONNECTED,DISCONNECTED,2018.01.06,2G,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3.5\t接通喇叭\n' +
  '3.5.1\t场景描述\n' +
  '当需要播放特定音频内容的时候，需要为外部的有源喇叭接通电源，使其工作。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通喇叭请求命令。\n' +
  '3.\tSCM接通有源喇叭外部电源，返回成功给PAD。\n' +
  '3.5.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.5.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.6\t断开喇叭\n' +
  '3.6.1\t场景描述\n' +
  '当完成音频播放后，出于节省功耗的考虑，需要尽快断开有源喇叭的电源供给。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开喇叭请求命令。\n' +
  '3.\tSCM断开有源喇叭外接电源，返回成功给PAD。\n' +
  '3.6.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_ DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.6.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.7\t接通前置PAD\n' +
  '3.7.1\t场景描述\n' +
  '当用户付费使用推车产品时，需要对前置PAD接通电源，以使其从关机状态下启动，供儿童娱乐。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通前置PAD请求命令。\n' +
  '3.\tSCM接通前置PAD外部电源，返回成功给PAD。\n' +
  '3.7.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.7.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.8\t断开前置PAD\n' +
  '3.8.1\t场景描述\n' +
  '当用户结束使用推车产品时，需要对前置PAD断开电源，以使云端可以发送命令使其从关机并不再自动重启。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开前置PAD请求命令。\n' +
  '3.\tSCM断开前置PAD外部电源，返回成功给PAD。\n' +
  '3.8.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.8.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '1\t版本记录\n' +
  '版本号\t修改点\t修改人\n' +
  'V1.0\t梳理通讯协议\t李庆春\n' +
  'V1.1\t1.\t去掉多余的关锁开关\n' +
  '2.\t开关锁等协议的调整\n' +
  '3.\t升级协议的调整\t李庆春\n' +
  'V1.2\t1.\t升级传输的分页报文规范和校验。\n' +
  '2.\t主PAD去掉通电启动的逻辑，和定时关机的逻辑。\t李庆春\n' +
  '\n' +
  '2\t通信规范\n' +
  '2.1\t通信架构\n' +
  ' \n' +
  '2.1\t模块解释\n' +
  '2.1.1\t控制板\n' +
  '控制板是整个车载硬件系统的核心，内嵌STM8S207K8单片机芯片，开放特定的端口和外部各个器件物理连接，通过单片机上的主程序和控制板上的物理电路控制各个器件。\n' +
  '2.1.2\t主PAD\n' +
  '主PAD是车载后置安卓PAD，安装位置在推车的扶手处。主PAD是用户的主要接口，用户通过主PAD进行开锁、暂停、关锁等一系列动作。通过5pin导线和控制板连接，其中3pin用于数据通信，2pin用于电源供给。\n' +
  '主PAD需要具备特性：1.定时开机。\n' +
  '2.1.3\t有源喇叭\n' +
  '有源喇叭的音频输入和主PAD的耳机口相连，电源输入通过2pin导线和控制板连接。单片机的2pin端口充当开关的角色，根据主PAD的命令决定是否连接到大电池的输出。\n' +
  '2.1.4\t大电池\n' +
  '大电池是主要的电源供给方，通过降压模块对主PAD、前部儿童PAD、小电池进行供电。\n' +
  '2.1.5\t前部儿童PAD\n' +
  '前部儿童PAD是坐在推车上的儿童的娱乐设施，通过USB和控制板连接，USB口充当电源开关的角色，单片机根据主PAD的命令决定是否为前部儿童PAD供电。\n' +
  '前部儿童PAD需要修改启动项，当检测到外部供电时，则启动系统。\n' +
  '2.1.6\t小电池\n' +
  '小电池责给控制板、有源喇叭、电机供电。\n' +
  '2.1.7\t锁\n' +
  '控制板接两组锁模块，每组包含：一个电机、一个关锁检测开关。主控制板根据主PAD下发的命令驱动电机正转或反转，并同时检测状态开关。锁的状态包括：打开、关闭、开锁中、关锁中。\n' +
  '2.1.8\t其他状态检测开关\n' +
  '其他状态检测包括：还车桩检测开关、安全带检测开关、预留的检测开关。三者承担的角色功能是一致的，都是检测pin口的电平输入，已确定相关器件是否物理连接。\n' +
  '2.2\t通信方式\n' +
  'PAD与SCM通过串口线直接连接，通过串口（UART）直接通讯。SCM周期性地自主睡眠和唤醒，一个时间周期为1.2秒，其中睡眠时间1秒和唤醒时间0.2秒。在SCM的唤醒时，SCM主动向PAD发送状态报文。PAD接收到状态报文后，才能检测到SCM处于唤醒状态，继而可以在这段唤醒时间内发送命令给SCM。\n' +
  '2.3\t报文结构\n' +
  '一个完整的报文包含三个部分：命令字、消息体、结束标志，三者通过英文冒号（:）分隔，依次排列构成一个字符序列。\n' +
  '命令字\t消息体\t结束标志\n' +
  '命令字：数据类型为字符序列，表示需要执行的动作。\n' +
  '消息体：数据类型为字符序列，表示命令需要携带的数据，如果有多个字段的数据，则用英文逗号（,）进行分隔。\n' +
  '结束标志：\\r\\n。\n' +
  '报文样例：\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,2018.01.06,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3\t通信命令\n' +
  '3.1\t开锁\n' +
  '3.1.1\t场景描述\n' +
  '当只有关锁检测开关时，锁模块包含两个核心组件：一个马达和一个关锁检测开关。锁的状态有两种：打开和关闭。当关锁检测开关为闭合状态时，认为锁是关闭状态，否则认为锁是打开状态。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送开锁请求命令。\n' +
  '3.\tSCM接收到开锁请求命令后，返回ACK，告知已收到消息。\n' +
  '4.\tSCM检测当前状态：\n' +
  'a)\t如果两个锁的状态都是开着的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是开着的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  'ii.\t如果锁2是非打开状态，则给锁输出正向固定时长电平（时长暂定3秒，具体时间后续根据实验数据进行调整）\n' +
  '5.\t检测两个锁的状态。\n' +
  '6.\tSCM发送开锁结果给PAD。\n' +
  ' \n' +
  '\n' +
  '3.1.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.1.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.1.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUNLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'UNLOCK_RES:UNLOCKED,UNLOCKED:\\r\\n\n' +
  '\n' +
  '3.2\t关锁\n' +
  '3.2.1\t场景描述\n' +
  '一个锁的模块包括：一个电机和一个关锁检测开关，在关锁的时候我们只需要判断关锁检测开关是否被压到，就可以确认是否关锁成功。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送关锁请求命令。\n' +
  '3.\tSCM接收到关锁请求命令后，发送ACK命令。\n' +
  '4.\t检测当前状态：\n' +
  'a)\t如果两个锁的状态都是关闭的，跳至步骤6。\n' +
  'b)\t如果两个锁的状态并不全是关闭的，则同时执行以下动作，并在动作全部完成后跳至步骤4：\n' +
  'i.\t如果锁1是非关闭状态，则向锁1输出反向电平固定时长（暂定3秒，具体时间后续根据实验数据进行调整），如果在这段时间内监听到锁1的中断消息，则执行：\n' +
  '1.\t当前时间的基础上继续给锁输出反向电平0.5秒，以使得开关被压到底，然后取消供电。 \n' +
  'ii.\t如果锁2是非关闭状态，则执行逻辑同上。\n' +
  '5.\t检测两个锁的状态。 \n' +
  '6.\tSCM发送关锁结果给PAD。\n' +
  ' \n' +
  '3.2.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ::\\r\\n\n' +
  '\n' +
  '3.2.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.2.4\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tLOCK_RES\n' +
  'lock1Status\tString\t锁1状态\tUNLOCKED\n' +
  'LOCKED\n' +
  'lock2Status\tString\t锁2状态\t同上\n' +
  '\n' +
  '报文样例\n' +
  'LOCK_RES:LOCKED,LOCKED:\\r\\n\n' +
  '\n' +
  '3.3\t固件升级\n' +
  '3.3.1\t场景描述\n' +
  '在SCM的使用过程中，会由于业务需求或者修复问题的情况，需要对SCM程序进行升级。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送固件升级请求命令。\n' +
  '3.\tSCM发送请求的ACK。\n' +
  '4.\tPAD和SCM同时执行：\n' +
  'a)\tPAD在6秒内轮询，每隔一秒向SCM发送“BOOT_READY”命令，询问SCM是否准备好，如果接收到SCM的ACK，则跳至步骤5。\n' +
  'b)\tSCM重启，进入BootLoader，然后监听PAD的BOOT_READY，接收后发送“BOOT_READY_ACK”。\n' +
  '5.\tPAD分页输送升级程序给SCM，从第一页开始，直至发送到最后一页，循环执行以下动作序列：\n' +
  'a)\tPAD发送当前页码命令给SCM：“PAGE_INDEX_<page_index>“。\n' +
  'b)\tSCM回复确认给PAD：“PAGE_INDEX_ACK“。\n' +
  'c)\tPAD发送当前页数据给SCM：<page_data>。\n' +
  'd)\tSCM回复确认给PAD：“PAGE_DATA_ACK”\n' +
  '6.\tPAD发送命令“DATA_DONE”给SCM，告知其所有分页数据以传输完成。\n' +
  '7.\tSCM回复确认“DATA_DONE_ACK”给PAD。\n' +
  '8.\tSCM使用新的升级程序进行升级。\n' +
  ' \n' +
  '3.3.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ::\\r\\n\n' +
  '\n' +
  '3.3.3\t请求确认报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tUPGRADE_REQ_ACK\n' +
  '\n' +
  '报文样例\n' +
  'UPGRADE_REQ_ACK::\\r\\n\n' +
  '\n' +
  '3.4\t状态上报\n' +
  '3.4.1\t场景描述\n' +
  'SCM自身会进行周期性的睡眠和自我唤醒，当SCM由睡眠状态切换到唤醒状态时，需要告知PAD，方便PAD发送命令给SCM。\n' +
  '同时出于业务的需要，携带一些设备的状态数据，包括但不限于：电池电量、两把锁的状态、SCM程序版本号、SCM芯片ID、一些检测开关的状态。\n' +
  '3.4.2\t请求报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSTATUS_REPORT\n' +
  'power\tint\t电池电量\t1-100\n' +
  'lock1Status\tString\t一个锁状态\tLOCKED\n' +
  'UNLOCKED、\n' +
  'lock2Status\tString\t另一个锁状态\t同上\n' +
  'speakerStatus\tString\t扬声器状态\tCONNECTED\n' +
  'DISCONNECTED\n' +
  'padfStatus\tString\t前置PAD状态\t同上\n' +
  'parkingPileStatus\tString\t停车桩状态\t同上\n' +
  'seatBeltStatus\tString\t安全带状态\t同上\n' +
  'reservedStatus\tString\t预留开关的状态\t同上\n' +
  'softVersion\tString\t软件版本\t版本号用日期格式如：2018.01.06\n' +
  'hardVersion\tString\t硬件版本\t如：2G（表示二代主板）\n' +
  'chipId\tString\t芯片ID\t\n' +
  '\n' +
  '报文样例\n' +
  'STATUS_REPORT:100,LOCKED,LOCKED,CONNECTED，CONNECTED，CONNECTED,DISCONNECTED,DISCONNECTED,2018.01.06,2G,C4B301CEFB09:\\r\\n\n' +
  '\n' +
  '3.5\t接通喇叭\n' +
  '3.5.1\t场景描述\n' +
  '当需要播放特定音频内容的时候，需要为外部的有源喇叭接通电源，使其工作。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通喇叭请求命令。\n' +
  '3.\tSCM接通有源喇叭外部电源，返回成功给PAD。\n' +
  '3.5.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.5.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.6\t断开喇叭\n' +
  '3.6.1\t场景描述\n' +
  '当完成音频播放后，出于节省功耗的考虑，需要尽快断开有源喇叭的电源供给。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开喇叭请求命令。\n' +
  '3.\tSCM断开有源喇叭外接电源，返回成功给PAD。\n' +
  '3.6.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_ DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.6.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tSPEAKER_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'SPEAKER_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.7\t接通前置PAD\n' +
  '3.7.1\t场景描述\n' +
  '当用户付费使用推车产品时，需要对前置PAD接通电源，以使其从关机状态下启动，供儿童娱乐。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送接通前置PAD请求命令。\n' +
  '3.\tSCM接通前置PAD外部电源，返回成功给PAD。\n' +
  '3.7.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.7.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_CONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_CONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n' +
  '3.8\t断开前置PAD\n' +
  '3.8.1\t场景描述\n' +
  '当用户结束使用推车产品时，需要对前置PAD断开电源，以使云端可以发送命令使其从关机并不再自动重启。\n' +
  '1.\tSCM唤醒后，向PAD发送状态上报命令。\n' +
  '2.\tPAD监听到SCM的状态上报命令后，向SCM发送断开前置PAD请求命令。\n' +
  '3.\tSCM断开前置PAD外部电源，返回成功给PAD。\n' +
  '3.8.2\t请求报文\n' +
  '调用方向\tPAD  SCM\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_REQ\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_REQ::\\r\\n\n' +
  '\n' +
  '3.8.3\t回复报文\n' +
  '调用方向\tSCM  PAD\n' +
  '\n' +
  '字段名称\t字段类型\t字段说明\t备注\n' +
  'command\tString\t命令\tPADF_DISCONNECT_RES\n' +
  'result\tString\t结果\tSUCCESS\n' +
  'FAIL\n' +
  '\n' +
  '报文样例\n' +
  'PADF_DISCONNECT_RES:SUCCESS:\\r\\n\n' +
  '\n'

export const str = s
